### ISSUE TITLE
Insufficient USB Permission

### ISSUE THREAD

**Issue by Arinerron** [benjholla/USBML4J#1]
`javax.usb.UsbPlatformException: USB error 3: Can't open device Bus 002 Device 011: ID 0a81:0701: Access denied (insufficient permissions)`

Linux Mint is my OS

**Comment by benjholla** [comment]
Sounds like an issue with the libusb library, which this project is using. Unfortunately Java isn't a very good language for interfacing with hardware, hence the library. I've only tested this particular code on Windows 7. You can checkout the libusb FAQ for some tips with *nix systems. 

https://github.com/libusb/libusb/wiki/FAQ#Running_libusb

**Comment by Arinerron** [comment]
@benjholla Okay. I exported it as a jar and ran it as sudo, and I got:

```
java.lang.NullPointerException
    at usbml4j.DefenseGrid.findMissileLaunchers(DefenseGrid.java:111)
    at usbml4j.DefenseGrid.findMissileLaunchers(DefenseGrid.java:100)
    at usbml4j.DefenseGrid.findMissileLaunchers(DefenseGrid.java:100)
    at usbml4j.DefenseGrid.findMissileLaunchers(DefenseGrid.java:91)
    at usbml4j.DefenseGrid.<init>(DefenseGrid.java:25)
    at usbml4j.DefenseGrid.getInstance(DefenseGrid.java:44)
    at test.TestMissileLauncher.main(TestMissileLauncher.java:13)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
javax.usb.UsbPlatformException: USB error 1: Unable to submit control message: Input/Output Error
    at org.usb4java.javax.ExceptionUtils.createPlatformException(ExceptionUtils.java:39)
    at org.usb4java.javax.AbstractIrpQueue.processControlIrp(AbstractIrpQueue.java:229)
    at org.usb4java.javax.ControlIrpQueue.processIrp(ControlIrpQueue.java:41)
    at org.usb4java.javax.ControlIrpQueue.processIrp(ControlIrpQueue.java:18)
    at org.usb4java.javax.AbstractIrpQueue.process(AbstractIrpQueue.java:104)
    at org.usb4java.javax.AbstractIrpQueue$1.run(AbstractIrpQueue.java:73)
    at java.lang.Thread.run(Thread.java:745)
[Launcher 1] Vertical Position: 0
[Launcher 1] Vertical Position: 0
[Launcher 1] Vertical Position: 0
[Launcher 1] Horizontal Position: 0
[Launcher 1] Horizontal Position: 0
[Launcher 1] Horizontal Position: 0
[Launcher 1] Fired: false
```

**Comment by benjholla** [comment]
Ok its slowly coming back to me now (sorry it's been a long time since I looked at this). So I remember testing on Windows and OSX now. There is a special bit of code I had to do for OSX. I assumed I would need to do the same for linux, but maybe not. Your stack trace shows it's breaking on line 111 of the DefenseGrid class, which makes me think the forceClaim is a bad idea on linux. I didn't fully understand what this was doing at the time myself...

Anyway, you could try commenting out the if block at this line and then running as root again.
https://github.com/benjholla/USBML4J/blob/master/USBML4J/src/usbml4j/DefenseGrid.java#L106

**Comment by Arinerron** [comment]
@benjholla Thank you, that fixed the NullPointerException. I still have to find out about this error:

```
javax.usb.UsbPlatformException: USB error 1: Unable to submit control message: Input/Output Error
    at org.usb4java.javax.ExceptionUtils.createPlatformException(ExceptionUtils.java:39)
    at org.usb4java.javax.AbstractIrpQueue.processControlIrp(AbstractIrpQueue.java:229)
    at org.usb4java.javax.ControlIrpQueue.processIrp(ControlIrpQueue.java:41)
    at org.usb4java.javax.ControlIrpQueue.processIrp(ControlIrpQueue.java:18)
    at org.usb4java.javax.AbstractIrpQueue.process(AbstractIrpQueue.java:104)
    at org.usb4java.javax.AbstractIrpQueue$1.run(AbstractIrpQueue.java:73)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by benjholla** [comment]
Ok maybe silly question, but you have the same USB missile launcher shown in the picture in the readme, right? The other models (like the gray one with the laser) won't work with this library (it could, but we'd have to update the constants and I didn't have a model to test with on hand at the time).

**Comment by Arinerron** [comment]
@benjholla Yep, it looks completely the same! Same model...

**Comment by benjholla** [comment]
Hmm I'm out of ideas at the moment. I think I'll have to dig out my model from the garage and play with it. Is there more to the stack trace that shows what line in the USBML4J library is triggering this error?

**Comment by Arinerron** [comment]
@benjholla This is all the output:

```
javax.usb.UsbPlatformException: USB error 1: Unable to submit control message: Input/Output Error
    at org.usb4java.javax.ExceptionUtils.createPlatformException(ExceptionUtils.java:39)
    at org.usb4java.javax.AbstractIrpQueue.processControlIrp(AbstractIrpQueue.java:229)
    at org.usb4java.javax.ControlIrpQueue.processIrp(ControlIrpQueue.java:41)
    at org.usb4java.javax.ControlIrpQueue.processIrp(ControlIrpQueue.java:18)
    at org.usb4java.javax.AbstractIrpQueue.process(AbstractIrpQueue.java:104)
    at org.usb4java.javax.AbstractIrpQueue$1.run(AbstractIrpQueue.java:73)
    at java.lang.Thread.run(Thread.java:745)
[Launcher 1] Vertical Position: 0
[Launcher 1] Vertical Position: 0
[Launcher 1] Vertical Position: 0
[Launcher 1] Horizontal Position: 0
[Launcher 1] Horizontal Position: 0
[Launcher 1] Horizontal Position: 0
[Launcher 1] Fired: false
```

I'm thinking probably the usb4java library executed `e.printStackTrace();` rather than throw the exception.

**Comment by Arinerron** [comment]
@benjholla My best guess as to the line is in MissileLauncher.java line 387:

```
device.syncSubmit(irp);
```

**Comment by benjholla** [comment]
I think you're right.

The stacktrace probably got printed here like you said: https://github.com/benjholla/USBML4J/blob/master/USBML4J/src/usbml4j/DefenseGrid.java#L71

Which would mean the MissleLauncher.initialize() got called which calls zero() which calls sendCommand(UsbDevice device, Command command) which calls sendMessage(UsbDevice device, byte command) where syncSubmit gets called.

Have you tried any other libraries by chance? I'm wondering if the retaliation library fails for this too.
https://github.com/codedance/Retaliation
